service: quick-start

provider:
  name: aws
  runtime: nodejs8.10

plugins:
  - serverless-offline

functions:
  hello:
    handler: handler.hello
    events:
      - http:
          path: /
          method: get
