service: kakao-payment-test

provider:
  name: aws
  runtime: nodejs6.10

plugins:
  - serverless-offline

region: ap-northeast-2

functions:
  hello:
    handler: handler.hello
    events:
      - http:
          path: /
          method: get
